### ISSUE TITLE
create a page for entering the buyer and seller names

### ISSUE THREAD

**Issue by ezl** [ezl/binkley-offer#58]
currently, the output PDF does *not* have the names of the buyer and seller, which are required for the contract.

These are the first 2 fields in the PDF: https://monosnap.com/file/Y9sm5v6ZexcyHaggQq8bxYkHPEZtMy

Please add a page titled "Buyer and Seller"

with 2 sections (in the same style as the fixtures page).

For now, both of these sections will only contain a single field.

Section=Buyer
Name: ____

Section=Seller
Name: ____

(This may sound silly, but a future item will be to include other information like their email addresses or other contact info)

**Comment by Tech-Dex** [comment]
This one is only Attached/Detached Property or both ?

**Comment by ezl** [comment]
for both

**Comment by ezl** [comment]
btw, personally, i do feel that we should treat each scraper as separate and each series of form fields as separate.

i believe we discussed this with @f-prime 

while it MIGHT be possible to use the same one for these TWO property types, we should build in a way that is extensible -- because really there are hundreds of different property types in different cities and different forms. And some of them will be signficantly different.

so if you generalize only slightly so that you can adapt to 2 PDFs <-> 2 sets of forms <-> 2 property types, then when we add a 3rd or 4th, we will run into the same problem.

**Comment by Tech-Dex** [comment]
I don't feel the same about the scraper. The issue that we had previous with scraper failing was that I didn't took first time when I created it in rush about fields that might be missing. So, what I've done I declared these missing fields as NULL before scraping, and if the scraper will fail for these fields there will be no problem, we will not use NULL value in our PDF-FILLER. From my PoV I think the one that we need to take care about is the PDF-FILLER and to create more version for this based on PDF/DATA. The PDF-FILLER will care only about populated fields from scraper so if there will be a NULL he will leave it blank.
The scraper it's should be a general one for a page in a website. We can declare all value entities from this page with his variations and the scraper will fill only what he will found
If we create more versions for scraper will be just code duplicate with a split of fields that we can declare NULL, the only different things will be that in a specific scraper we give specific fields that SHOULD be populated... and if there will be anything different on a page the scraper will fail and that's why I think the best version is a scraper that "try-catch" to get all fields that we want and to populate only what we found and other fields declared ( other fields for others version of the page ) to be leaved as NULL.
@ezl

**Comment by Tech-Dex** [comment]
The method that is taking care about this is this one:

def parse_bs4():
    global page
    hoa_dues = None
    tax = None
    tax_exemptions = None
    tax_year = None
    parcel_identification_number = None
    soup = BeautifulSoup(page.content, 'html.parser')
    street_address_span = soup.find(class_='street-address')
    city_state_zip_span_locality = soup.find(
        class_='citystatezip').find(class_='locality')
    city_state_zip_span_region = soup.find(
        class_='citystatezip').find(class_='region')
    city_state_zip_span_postal_code = soup.find(
        class_='citystatezip').find(class_='postal-code')
    agent_details = soup.find(
        class_='agent-basic-details font-color-gray-dark')
    divs_details = soup.findAll(
        class_='keyDetail font-weight-roman font-size-base')
    for div in divs_details:
        if 'HOA Dues' in div.get_text():
            hoa_dues = div.find(class_='content text-right')

    divs_details = soup.findAll(
        class_='amenity-group')
    for div in divs_details:
        if 'Financial Information' in div.get_text():
            temp = div.find(
                class_='no-break-inside').findAll(class_='entryItemContent')
            tax = temp[0]
            tax_year = temp[1]
            for li in div.findAll(class_='entryItem'):
                if 'Homeowner' in li.get_text():
                    tax_exemptions = li

        if 'Property Information' in div.get_text():
            for span in div.findAll(class_='entryItemContent'):
                if 'Parcel Identification Number' in span.get_text():
                    parcel_identification_number = span

    details_dict = dict()
    details_dict.update({
        'property_street_address': street_address_span.get_text().strip(),
        'property_locality': city_state_zip_span_locality.get_text().strip()[:-1],
        'property_region': city_state_zip_span_region.get_text().strip(),
        'property_postal_code': city_state_zip_span_postal_code.get_text().strip(),
        'agent_details_name': agent_details.get_text().split(sep='•')[0][10:].strip(),
        'agent_details_company': agent_details.get_text().split(sep='•')[1].strip()
    })
    if hoa_dues:
        details_dict.update({
            'hoa_dues': hoa_dues.get_text()[1:].strip()
        })
    if tax:
        details_dict.update({
            'tax': tax.get_text().split(sep='$')[1].strip()
        })
    if tax_year:
        details_dict.update({
            'tax_year': tax_year.get_text().split(sep=':')[1].split(sep='20')[1].strip()
        })
    if tax_exemptions:
        details_dict.update({
            'tax_exemptions': tax_exemptions.get_text().split(sep=':')[1].strip()
        })
    if parcel_identification_number:
        details_dict.update({
            'parcel_identification_number': parcel_identification_number.get_text().split(sep=':')[1].strip()
        })
    return details_dict

The problem that we had was related to hoa_dues, tax, tax_year, tax_exemptions, parcel_identification_number that might be partial missing on the other version of the web page. I will update tof for every field to check `if field:` and then update in in the dict that we return to frontend.

**Comment by ezl** [comment]
@Tech-Dex ok no problem. I was worried that if we expand scope it may require different scrapers and different form markup.

technical implementation is up to you.

Basically, for now, the only requirement is to make it work across these 2. If in the future when we add more, it becomes an issue, we can revisit then. No need to optimize prematurely.

**Comment by ezl** [comment]
oops, just meant to comment, not to close 😇

**Comment by Tech-Dex** [comment]
@gmit08 Can you give me an UI Design for this page?

**Comment by gmit08** [comment]
@Tech-Dex clarifying the vision on this with @ezl tomorrow. In the meantime, can you take a look at this card? https://github.com/ezl/binkley-offer/projects/1#card-48462115

**Comment by ezl** [comment]
![image](https://user-images.githubusercontent.com/157627/97923916-71310c00-1d24-11eb-98cf-1986d0619757.jpeg)

Is this enough for you Tech-Dex ?

The boxes around the buyer section and seller section are like the grey containers on the fixtures page.

Make the title font size match other pages.

Same next button as all other pages.

**Comment by gmit08** [comment]
@Tech-Dex We'd like you to have a try at the front-end for this but please make a ticket for Carlos for the FE portion if you need to delegate.

**Comment by gmit08** [comment]
@Tech-Dex This failed testing on my MS/Chrome desktop:
![image](https://user-images.githubusercontent.com/59035440/98010631-e8b67800-1dc4-11eb-93a2-d5113e5fe4e9.png)

Can you debug and move back to ready for review when complete?

**Comment by Tech-Dex** [comment]
Can you try another property? This one might be a previous version that was already saved and cached in BE ( what is happening is that the BE is generating the PDF only one time and if you try to create a new PDF for the same property you will get the one that was already generated to avoid waiting time -> This one will be different when we will have user)

**Comment by gmit08** [comment]
@Tech-Dex Sure- will try now

**Comment by gmit08** [comment]
@Tech-Dex I tried it for 233 View Drive and am now getting the spinning circle with no download at all. I also noticed that some fields were populated from when I filled out the form earlier (property details checkboxes as well as some others). Could the pre-population be related to not being able to download?

**Comment by gmit08** [comment]
> @Tech-Dex I tried it for 233 View Drive and am now getting the spinning circle with no download at all. I also noticed that some fields were populated from when I filled out the form earlier (property details checkboxes as well as some others). Could the pre-population be related to not being able to download?

I might say this requires clearing my cache, but users should not have to clear their cache each time I think. Thank you for looking into this

**Comment by ezl** [comment]
Weighing in here --

@gmit08 I see you tried an address 233 View Drive that may have failed.

An important thing to note is that:
(A) Redfin supports properties from all around the country
(B) the scrapers that we have built ONLY are built to work for 2 types of properties (single attached, single detached) and have ONLY been built for Chicago.

So if you're choosing a specific property that does NOT meet these criteria, it's untested, and not known to work, nor is it EXPECTED to work.

To try a single attached: use any of 1000 w washington units or 924 w armitage.
To try single detached: use 1729 winchester

(all in Chicago IL)

This MAY solve the issue you're having.

However, brings up a separate issue -- we should have a better way of failing more gracefully -- basically if something does NOT meet our input criteria, we shouldn't jsut randomly fail -- we should have some way of notifying the user that it broke when trying to retrieve information.

**Comment by gmit08** [comment]
@Tech-Dex  Upon testing the 2 Chicago addresses above (and re-testing 1832 n orleans, Chicago) I was still unable to get either to work. Can you provide an address that you've been confirming and successfully gotten to work? This may warrant a couple new cards that you can create as bugs, but I need to confirm the buyer and seller name showing up. Perhaps a screen recording and noting which OS/browser it's working on for you?

**924 w armitage**-- I received this error message. Can you look into why?
![image](https://user-images.githubusercontent.com/59035440/98198204-734ac480-1ef6-11eb-9302-dfd2d4d4f773.png)

**1000 w washington**--- did not return what I entered ("test" for buyer and "test 2" for seller) but instead show BUTER and SELLER. If this can be fixed by frontend, feel free to loop in Carlos! Many other fields did not make it to the PDF (Attached)
![image](https://user-images.githubusercontent.com/59035440/98198476-097eea80-1ef7-11eb-8cfc-9ef82ae9b844.png)
[1000 w washington.pdf](https://github.com/ezl/binkley-offer/files/5492024/1000.w.washington.pdf)

**1832 n orleans** PDF generate but buyer/seller names came up blank in addition to most other fields (PDF attached). I noticed that Redfin address says Unit T in search but that Unit T did not make it into the Confirm Details page. Could this be related for this property (maybe the scraper needs to be adjusted?)? -- feel free to make a new issue.
![image](https://user-images.githubusercontent.com/59035440/98198928-151ee100-1ef8-11eb-8827-73108ab889a6.png)
![image](https://user-images.githubusercontent.com/59035440/98198994-41d2f880-1ef8-11eb-80ce-9d6698c9db89.png)
[1832 n orleans.pdf](https://github.com/ezl/binkley-offer/files/5492027/1832.n.orleans.pdf)

cc @ezl

**Comment by ezl** [comment]
@gmit08 ffffff. i know exactly what is going on here. ticketing it separately.

re: 924 armitage - i screwed up -- 924 w armitage is NOT a valid address. 824 w armitage is. Typo. 824 w armitage is a condo building ("single attached") and has a lot of different units.

**Comment by gmit08** [comment]
@ezl @Tech-Dex thanks, I got 824 w armitage to work! Nice! Will discuss others at standup
